version: '3.8'

networks:
  dokploy-network:
    external: true

services:
  app:
    build: .
    restart: always

    networks:
      - dokploy-network

    volumes:
      - bravia360_uploads:/app/uploads

  
volumes:
  bravia360_uploads:
    driver: local
