version: '3.8'

networks:
  dokploy-network:
    external: true

services:
  app:
    image: bravia360:latest

    networks:
      - dokploy-network

    volumes:
      - bravia360_uploads:/app/uploads

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"

        - "traefik.http.routers.tour360.rule=Host(`tour360.braviaglobal.com.br`)"
        - "traefik.http.routers.tour360.entrypoints=websecure"
        - "traefik.http.routers.tour360.tls=true"
        - "traefik.http.routers.tour360.tls.certresolver=letsencrypt"

        - "traefik.http.services.tour360.loadbalancer.server.port=5000"

volumes:
  bravia360_uploads:
    driver: local
